In [7]:
#气温为数组a，计算气温最值/均数/>30的天数
import numpy as np
a=np.array([28,30,29,31,32,30,29])
print('最高气温：',np.max(a))
print('最低气温：',np.min(a))
print('平均气温：',np.mean(a))
print('气温超过30度的天数：',np.sum(np.where([a>30],[1],[0])))
print('气温超过30度的天数：',len(a[a>30]))
print('气温超过30度的天数：',np.count_nonzero(a>30))#非零计数

最高气温： 32
最低气温： 28
平均气温： 29.857142857142858
气温超过30度的天数： 2
气温超过30度的天数： 2
气温超过30度的天数： 2


In [9]:
#成绩为b，计算平均分/方差/中位数，并将成绩转换为10分制
b=np.array([85,90,78,92,88])
print('平均分为：',np.mean(b))
print('成绩方差为：',np.var(b))
print('成绩中位数为：',np.median(b))
print(b/10)

平均分为： 86.6
成绩方差为： 23.84
成绩中位数为： 88.0
[8.5 9.  7.8 9.2 8.8]


In [12]:
#矩阵A、B的和，*，点积
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [17]:
#生成（x，y）随机数组，范围[1,10],计算每列最大值与每行最小值，数组中的奇数替换为-1
arr=np.random.randint(1,10,(3,4))
print(arr)
print('每列的最大值：',np.max(arr,axis=0))#axis=0,列
print('每行的最小值:',np.min(arr,axis=1))#axis=1,行
print(np.where(arr%2==1,-1,arr))
arr[arr%2==1]=-1#布尔索引
print(arr)

[[1 5 4 4]
 [8 1 4 3]
 [5 1 7 8]]
每列的最大值： [8 5 7 8]
每行的最小值: [1 1 1]
[[-1 -1  4  4]
 [ 8 -1  4 -1]
 [-1 -1 -1  8]]
[[-1 -1  4  4]
 [ 8 -1  4 -1]
 [-1 -1 -1  8]]


In [5]:
import numpy as np
arr=np.random.randint(1,100,50)
arr1=np.where(arr<60,'不及格',np.where(arr<80,'及格',np.where(arr<90,'良好','优秀')))
print(arr1)
print('不及格人数：',np.sum(arr<60))
print('及格人数：',np.sum((arr>=60) & (arr<80)))
print('良好人数：',np.sum((arr>=80) & (arr<90)))
print('优秀人数：',np.sum(arr>=90))
print('方差：',np.var(arr))

['不及格' '优秀' '不及格' '不及格' '不及格' '及格' '良好' '不及格' '不及格' '不及格' '不及格' '及格' '不及格'
 '及格' '不及格' '不及格' '及格' '不及格' '优秀' '优秀' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格'
 '不及格' '及格' '不及格' '不及格' '不及格' '优秀' '不及格' '及格' '优秀' '及格' '良好' '不及格' '不及格'
 '优秀' '不及格' '不及格' '及格' '优秀' '不及格' '及格' '不及格' '良好' '优秀' '及格']
不及格人数： 29
及格人数： 10
良好人数： 3
优秀人数： 8
