#题目5

In [1]:
import numpy as np

In [7]:
arr=np.arange(1,13)
print(arr)
arr1=arr.reshape(3,4)
print(arr1)
print('每行求和为：',np.sum(arr1,axis=1))
print('每列平均值为：',np.mean(arr1,axis=0) )
print(arr.reshape(1,12))
      



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行求和为： [10 26 42]
每列平均值为： [5. 6. 7. 8.]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


#随机数组

In [12]:
arr=np.random.randint(1,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))


[[16 10  9 10  6]
 [ 6  6 11  6  9]
 [16  5 10 10  6]
 [17 11 19 16  8]
 [ 8  1 14  3  6]]
[16 11 16 17 11 19 16 14]
[[ 0 10  9 10  6]
 [ 6  6  0  6  9]
 [ 0  5 10 10  6]
 [ 0  0  0  0  8]
 [ 8  1  0  3  6]]


#统计函数应用

In [15]:
arr=np.array([120,135,110,125,130,140])
print('总和;',np.sum(arr))
print('均值：',np.mean(arr))
print('方差：',np.var(arr))
print('标准差：',np.std(arr))
print('销售额最大月份：',np.argmax(arr)+1)
print('销售额最小月份：',np.argmin(arr)+1)

总和; 760
均值： 126.66666666666667
方差： 97.22222222222223
标准差： 9.860132971832694
销售额最大月份： 6
销售额最小月份： 3


#数组拼接

In [17]:
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.concatenate((A,B))
print(C)
D=np.reshape(C,(2,3))
print(D)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#唯一值与排序

In [24]:
arr=np.array([2,1,2,3,1,4,3])
print('唯一元素：',np.unique(arr))
u_arr,counts=np.unique(arr,return_counts=True)
print('唯一元素出现次数：',counts)#numpy方法
d=[]
for i in range(len(u_arr)):
    d=d+[len(arr[arr==u_arr[i]])]
print(d)    
    #python方法


唯一元素： [1 2 3 4]
唯一元素出现次数： [2 2 2 1]
[2, 2, 2, 1]


#综合运用

In [27]:
money=np.array([20,25,22,30,28])
cost=np.array([15,18,16,22,28])
profit=money-cost
print('利润：',profit)
print('利润的平均值：',np.mean(profit))
print('利润的标准差：',np.std(profit))
print('利润最大月份：',np.argmax(profit)+1)

利润： [5 7 6 8 0]
利润的平均值： 5.2
利润的标准差： 2.7856776554368237
利润最大月份： 4
